cor_index:
    path:     /
    defaults: { _controller: "AppBundle:Cor:index" }
    methods:  GET

cor_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cor:show" }
    methods:  GET

cor_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cor:new" }
    methods:  [GET, POST]

cor_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cor:edit" }
    methods:  [GET, POST]

cor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cor:delete" }
    methods:  DELETE
