modelo_index:
    path:     /
    defaults: { _controller: "AppBundle:Modelo:index" }
    methods:  GET

modelo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Modelo:show" }
    methods:  GET

modelo_new:
    path:     /new
    defaults: { _controller: "AppBundle:Modelo:new" }
    methods:  [GET, POST]

modelo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Modelo:edit" }
    methods:  [GET, POST]

modelo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Modelo:delete" }
    methods:  DELETE
