numerorodas_index:
    path:     /
    defaults: { _controller: "AppBundle:Numerorodas:index" }
    methods:  GET

numerorodas_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Numerorodas:show" }
    methods:  GET

numerorodas_new:
    path:     /new
    defaults: { _controller: "AppBundle:Numerorodas:new" }
    methods:  [GET, POST]

numerorodas_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Numerorodas:edit" }
    methods:  [GET, POST]

numerorodas_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Numerorodas:delete" }
    methods:  DELETE
